// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    CounterComponent: typeof import('./src/components/CounterComponent.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    NavMenu: typeof import('./src/components/NavMenu.vue')['default']
    OiHome: typeof import('virtual:vite-icons/oi/home')['default']
    OiListRich: typeof import('virtual:vite-icons/oi/list-rich')['default']
    OiPlus: typeof import('virtual:vite-icons/oi/plus')['default']
  }
}

export { }
