//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

module Features.Base {
	export interface IBaseResult
	{
		IsSuccessful: boolean;
		Message: string;
		Errors: { [key:string]: string };
	}
}
module Features.Account {
	export interface ILoginCommand
	{
		Email: string;
		Password: string;
		RememberMe: boolean;
	}
	export interface ILoginResult extends Features.Base.IBaseResult
	{
		RequiresTwoFactor: boolean;
		IsLockedOut: boolean;
		RequiresEmailConfirmation: boolean;
		Token: string;
	}
	export interface IResetPasswordCommand
	{
		Code: string;
		Email: string;
		Password: string;
		ConfirmPassword: string;
	}
}
module Features.Account.Manage {
	export interface IMfaEnableResult extends Features.Base.IBaseResult
	{
		SharedKey: string;
		AuthenticatorUri: string;
		QrCodeBase64: string;
	}
	export interface IMfaInfo extends Features.Base.IBaseResult
	{
		HasAuthenticator: boolean;
		RecoveryCodesLeft: number;
		IsMfaEnabled: boolean;
		IsMachineRemembered: boolean;
	}
	export interface IUserProfileCommand
	{
		Email: string;
		PhoneNumber: string;
		IsEmailConfirmed: boolean;
	}
}
