// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Authorized: typeof import('./src/areas/account/components/Authorized.vue')['default']
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    CounterComponent: typeof import('./src/components/CounterComponent.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginDisplay: typeof import('./src/areas/account/components/LoginDisplay.vue')['default']
    ManageNav: typeof import('./src/areas/account/components/ManageNav.vue')['default']
    NavMenu: typeof import('./src/components/NavMenu.vue')['default']
    NotAuthorized: typeof import('./src/areas/account/components/NotAuthorized.vue')['default']
    OiCheck: typeof import('virtual:vite-icons/oi/check')['default']
    OiFork: typeof import('virtual:vite-icons/oi/fork')['default']
    OiHome: typeof import('virtual:vite-icons/oi/home')['default']
    OiListRich: typeof import('virtual:vite-icons/oi/list-rich')['default']
    OiPlus: typeof import('virtual:vite-icons/oi/plus')['default']
    PassThrough: typeof import('./src/components/PassThrough.vue')['default']
    TwAlertDanger: typeof import('./src/components/TwAlertDanger.vue')['default']
    TwAlertSuccess: typeof import('./src/components/TwAlertSuccess.vue')['default']
    TwCard: typeof import('./src/components/TwCard.vue')['default']
    TwFormGroup: typeof import('./src/components/TwFormGroup.vue')['default']
    VuelidateFullInput: typeof import('./src/components/VuelidateFullInput.vue')['default']
    VuelidateInput: typeof import('./src/components/VuelidateInput.vue')['default']
    VuelidateMessages: typeof import('./src/components/VuelidateMessages.vue')['default']
  }
}

export { }
